name: Build

on: 
  push:
    branches: 
      - menu
      - main
      - logic
      - developer

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install SFML
        run: sudo apt-get install libsfml-dev
        
      - name: Check codestyle
        run: git ls-files *.{cpp,hpp} | xargs clang-format -i --verbose && git diff --exit-code        
      
      - name: Build application
        run: make
